-- ==========================================================================
-- Fix: dragging a project to a new position failed with 428C9,
-- "cannot insert a non-DEFAULT value into column id".
--
-- The console reordered with an upsert, which PostgREST sends as
-- INSERT ... ON CONFLICT. `id` is GENERATED ALWAYS, so Postgres rejects the
-- insert half before it ever reaches the conflict clause.
--
-- The obvious fix is `alter column id set generated by default`, but that
-- permanently allows explicit ids and a hand-written one can collide with the
-- sequence, producing duplicate-key errors much later and far from the cause.
-- A function keeps the column strict and still does the whole reorder in one
-- statement, so a half-applied order is not possible.
--
-- SECURITY INVOKER on purpose: row-level security still applies, so this is
-- only usable by staff, exactly like a direct update.
-- ==========================================================================

create or replace function public.reorder_projects(items jsonb)
returns void
language sql
security invoker
as $$
  update public.projects p
  set sort_order = x.sort_order
  from jsonb_to_recordset(items) as x(id bigint, sort_order int)
  where p.id = x.id;
$$;

select p.name, p.sort_order
from public.projects p
order by p.sort_order, p.id;
